on:
 release:
   types: [published]
 push:
   tags:
     - '!refs/tags/*'
   branches:
     - '*'
   paths-ignore:
     - 'README.md'

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.2.1
        with:
          php-version: '7.4'
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install requirements
        run: composer install
      - name: Run tests
        run: php bin/phpunit

  build_and_pub:
    needs: [run_tests]
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
    steps:
      - name: Login to docker.io
        run:  echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@master
      - name: Build image
#        run: docker build -t $LOGIN/$NAME:${GITHUB_REF:11} -f Dockerfile .
        run: docker build -t narkov/ci-php-test:${GITHUB_REF##*/} .
      - name: Push image to docker.io
        run: docker push $LOGIN/$NAME:${GITHUB_REF:11}

  deploy:
    needs: [build_and_pub]
    runs-on: [ubuntu-latest]
    steps:
      - name: Set tag to env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})
      - name: Send webhook for deploy
        run: "curl --silent --show-error --fail -X POST ${{ secrets.DEPLOYMENT_SERVER }} -H 'Authorization: ${{ secrets.DEPLOYMENT_TOKEN }}' -H 'Content-Type: application/json' -d '{\"owner\": \"${{ secrets.DOCKER_LOGIN }}\", \"repository\": \"${{ secrets.DOCKER_NAME }}\", \"tag\": \"${{ env.RELEASE_VERSION }}\", \"ports\": {\"8000\": 8000}}'"
