on:
 release:
   types: [published]

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.2.1
        with:
          php-version: '7.4'
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install requirements
        run: composer install
      - name: Run tests
        run: php bin/phpunit

  build_and_pub:
    needs: [run_tests]
    runs-on: [ubuntu-latest]
    env:
      LOGIN: ${{ secrets.DOCKER_LOGIN }}
      NAME: ${{ secrets.DOCKER_NAME }}
